# 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
appId: 2021000116660863
  # 商户私钥，您的PKCS8格式RSA2私钥
privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDWkK+2Z1a6XqlZiaE0NKJ+3kvUWLyHA9LBzT+OroQnU2HDULBG50auiSU5LcjVwLd6c5T65zFHVJ5DjLjwj2CmFW4ab+upoiS/1XRQebUejb7Lm5Rurb4s0Frs+hf5uexDntgKHhu0ajE51NspBrbkE9aiKPK+bIJn86euFNtwywp42IhTeQxO6F1qWtHy4ZTxAswxl8eI7+jnYH6CiO9yUiFoIJoG/AW738cf18dQGq/9JCh8vmwc0nA8YFoJVtEcPiLIazWvdjTcgWczZfHkonoHpJRQQJBOIm2lk6sevdO3URGBhvYTxWSW8Pj2bYVBb2my7bGTowdAdJ38cjS/AgMBAAECggEAYLMUfcBU9elzqUa9wCl4knTc9/aGANNYSL+XxVYheRe7F6tlxo607DQi8oIP4UXZavZsTiejreIU8ZyaPNBhXniKBqAqNWk95rbslNhFKF/5fQnA+6CR9OByGhsccw+3y0HrW6P2GHlDdizYGMVN57yJHswVmnyMyQympW4A9/O2o1QVh+galcWMudPpwZPPYwQd+CFZOGJWxzW1J9zZjC80KTm8D9Fj9ZGicibiiAFyopqMAkqeQVf6YYpta+qBX+t9ezuMu96wMfWXQZm+koDXyF4g+QTVtEM7ERpH3hXQdf+QSJOUzgGWU5dQYlPSD3exIOwJnb+V0ZDou9bfAQKBgQDreFkyaicvJlG9IVDeQLEGILqeGcvHlT62Tu7jsXiooC08EHy/F3knwyCL8Z4DvS5T3vP99EM69IFKJql+QADjTlfGsDI09BPHjY1mSu2Cjg+WuRmRdWAxnuIWyfUaQl5v4wy8MVqgJwCXG9heQihflYTohSf+ri9y1h7baDn9dQKBgQDpRb5bfkfbg0hj07YowyEn/m5yWuxM1X+yX8E80FpRjzmx0dV0yR6R6mom5pY4xEIcA3Ka49AO8GApvyMs27YOcSa6nWoGoX3H3BPR1XZ97pH3eVfliCyD6QCxGY/tSWTPnlIliY1u34n3LZhuYdvaM7x1UQVmQtdCK1EYK+/e4wKBgHZAKgs3ZBY5mDLy2DnFIyGArjdXnQ7N1ICZgz61kXKdfhn77anJj/5375BX9pLKHsnf3YhbcqfYwlUKtXPBkLCWV15gfdY5/PTqEWidmElILmvy6PQzjetdbw0ivwRA8EwgKfUYk/p5m8JHKZGsh7n4zJY4yK0NrKZvAXAOF5FBAoGBAIlxVGVoFEKcKYzX8t41ilWcLcsnE096A9E/ZgXE5VJkxyOkdNZooaBrs7vT5PLxf9otldr5G1+R9bbjLYCCu9Pqi10s3omloQye+PaLhVNRu6NKVaWiBEh8grHWU90Ff2Zs7A297B1FjG6c6NEwy27XSNT+teW4wEf2acOKL7ztAoGALuAMaqir7msRYz+UC+yBWSubLKCkmqgV00cOYu16yBnmyub2Rn4W7uABCuRx5U9vdiddh8gUmmrLZQR4A4Xg+7wbIQ6FwAXLZnkUe1EniMxVu41UIjdygTOlnIoV1z2Hw32b47w4eWsmSUOlfclWM8aW2hjU7RxFbEPCLYWZuuc=
  # 支付宝公钥,查看地址：https://openhome.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg6gpbPkXSYXDp3NQg/O5JaVbdTGYx6rMJcNuM0JOqskIgKIrzc2Y/bflTCVnorG7CI9lRu4FRZIJMeiGq4yk8MI9HAj69CaNEKnur5hp10wy9sdOYB+EeAIZVqI3sfODsX+uCrwPback2pdkJyZ8ZYyYDvIwViyM5x8MbLfWFSG0U8OvFjCXn9tXHAFbByL8CtU/+RwpQJhJjVvGb3BmweErbiC5zfnWNiS9K6spNh2kkv1+/TeF/eFqUg/6aA0LAeA8HrH1hCRf+iiOUxjnFruT0/I96akKcq4//Nifuw4plToQKjUwBdsI0/upyG6CIue46rsFYZJqGQ96ERsd8wIDAQAB
  # 服务器异步通知页面路径需http://格式的完整路径，不能加?id=123这类自定义参数
notifyUrl: http://127.0.0.1:8765/alipay/notify
  # 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id:123这类自定义参数
returnUrl: http://127.0.0.1:8765/alipay/return

payVipNotifyUrl: http://127.0.0.1:8765/notifyVipPay
# 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id:123这类自定义参数
payVipReturnUrl: http://127.0.0.1:8765/recharVipPay
  # 签名方式
signType: RSA2
  # 字符编码格式
charset: utf-8
  # 返回格式
format: json
  # 支付宝网关
gatewayUrl: https://openapi.alipaydev.com/gateway.do
  # 支付宝网关
logPath: "C:\\"
  # 提现账号真实姓名
payer_show_name: 曹学亮
