eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
  servlet:
    session:
      timeout: 600m
spring:
  application:
    name: web
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: html
    encoding: utf-8
  resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  devtools:
    restart:
      additional-paths: resources/**,static/**,templates/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

feign:
  hystrix:
    enabled: true
### Hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#ribbon的超时时间
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
  # 饥饿加载
  eager-load:
    # 是否开启饥饿加载
    enabled: true
    # 饥饿加载的服务
    clients: service


#FastDfs的配置	====================================
fdfs:
  trackerList: 49.233.48.96:22122
  resHost: 49.233.48.96
  storagePort: 8888
#视频转化配置	====================================
video:
  videoImport: /vtuweb/videoImport/
  videoOutput: /vtuweb/videoOutput/
  videoLog: /vtuweb/videoLog/logo.png
  videoDown: /vtuweb/down/
  indexPath: /vtuweb/indexFile/vtuweb.com.html



