eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
  connection-timeout: 18000000
spring:
  application:
    name: service
  profiles:
    active: dev
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.vtu.model  # 注意：对应实体类的路径
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
#mybatis 查询语句展示sql
#logging:
#  level:
#    com.winter.mapper: DEBUG

